name: siam #e siam_eu
batch_size: 32
epochs: 128
lr: 4.5 #e4.1
eval_rate: 1 #e3
crop_sizes: [40] #e56
fraction: 8 #e8
smoothness: 2
negative_frac: 1/3
layer_pool: True
filter_size: 3
emb_channels: 16
residual: 2 #e:0
width: 512
output_size: 64 #width//fraction
crops_multiplier: 1
batching: crops_multiplier
eval_limit: 20000
#tolerance: 32

