name: siam #e siam_eu
width: 512
height: 324 #asi
batch_size: 2 #32
epochs: 2 #was 128
lr: 4.5 #e4.1
eval_rate: 1 #e3 ## should be whole divisor of epochs
crop_sizes: [56] #e56
fraction: 8 #e8
smoothness: 2
negative_frac: 0.33
layer_pool: True
filter_size: 3
emb_channels: 16
residual: 0 #e:0
crops_multiplier: 1
batching: crops_multiplier
eval_limit: 20000
tolerance: 50

train:
  help:
eval:
  help: 30

#tolerance: 32

